import type { BestiaryEntry } from '../types.js';

/**
 * Bestiário de Tibia, ordenado por ameaça — de rato de Rookgaard a Ferumbras.
 * `threat` é a referência que o Mestre usa para calibrar encontros.
 */
export const tibiaBestiary: BestiaryEntry[] = [
  {
    id: 'rat',
    name: 'Rato',
    description: 'O primeiro inimigo de todo mundo. Guincha, morde, morre.',
    threat: 1,
    vitals: { hp: 20 },
    attributes: { fist: 8 },
    attacks: [{ name: 'Mordida', damage: '1d4' }],
    loot: [{ itemId: 'gold-coin', chance: 0.7, quantity: [1, 4] }],
    experience: 5,
    habitats: ['rookgaard-sewers', 'thais'],
  },
  {
    id: 'cave-rat',
    name: 'Rato de Caverna',
    description: 'Maior, mais gordo, mais atrevido. Anda em bandos nos esgotos.',
    threat: 2,
    vitals: { hp: 30 },
    attributes: { fist: 12 },
    attacks: [{ name: 'Mordida', damage: '1d6' }],
    loot: [
      { itemId: 'gold-coin', chance: 0.8, quantity: [2, 10] },
      { itemId: 'brown-mushroom', chance: 0.15 },
    ],
    experience: 10,
    habitats: ['rookgaard-sewers', 'rookgaard-mines'],
  },
  {
    id: 'snake',
    name: 'Cobra',
    description: 'Pequena e venenosa. Fácil de matar, chata de sobreviver.',
    threat: 2,
    vitals: { hp: 25 },
    attributes: { fist: 10 },
    attacks: [{ name: 'Picada Venenosa', damage: '1d4', element: 'veneno', description: 'Aplica "envenenado".' }],
    loot: [{ itemId: 'gold-coin', chance: 0.4, quantity: [1, 5] }],
    experience: 8,
    habitats: ['rookgaard', 'venore-swamp'],
    weaknesses: ['gelo'],
  },
  {
    id: 'wolf',
    name: 'Lobo',
    description: 'Nunca vem sozinho. Se você vê um, há três que você não viu.',
    threat: 3,
    vitals: { hp: 45 },
    attributes: { fist: 18 },
    attacks: [{ name: 'Dentada', damage: '1d8+2' }],
    loot: [
      { itemId: 'gold-coin', chance: 0.6, quantity: [3, 12] },
      { itemId: 'health-potion', chance: 0.05 },
    ],
    experience: 22,
    habitats: ['rookgaard', 'thais-outskirts'],
  },
  {
    id: 'troll',
    name: 'Troll',
    description: 'Burro, forte e curioso quanto ao seu inventário. Rouba o que não consegue comer.',
    threat: 4,
    vitals: { hp: 50 },
    attributes: { club: 20, fist: 15 },
    attacks: [{ name: 'Porretada', damage: '1d10+2' }],
    loot: [
      { itemId: 'gold-coin', chance: 0.85, quantity: [5, 20] },
      { itemId: 'club', chance: 0.2 },
      { itemId: 'rope', chance: 0.1 },
    ],
    experience: 20,
    habitats: ['rookgaard-mines', 'thais-outskirts'],
  },
  {
    id: 'goblin',
    name: 'Goblin',
    description: 'Pequeno, covarde e organizado — a combinação mais irritante possível.',
    threat: 4,
    vitals: { hp: 55 },
    attributes: { sword: 22, distance: 18 },
    attacks: [
      { name: 'Faca Enferrujada', damage: '1d8+3' },
      { name: 'Pedrada', damage: '1d6', description: 'A três passos ou mais.' },
    ],
    loot: [
      { itemId: 'gold-coin', chance: 0.9, quantity: [8, 25] },
      { itemId: 'hand-axe', chance: 0.15 },
    ],
    experience: 25,
    habitats: ['rookgaard-mines'],
  },
  {
    id: 'orc',
    name: 'Orc',
    description: 'Guerreiro tribal das terras a leste de Thais. Ataca em formação e sem hesitar.',
    threat: 5,
    vitals: { hp: 70 },
    attributes: { axe: 28, shielding: 15 },
    attacks: [{ name: 'Machadada', damage: '2d6+3' }],
    loot: [
      { itemId: 'gold-coin', chance: 0.9, quantity: [10, 30] },
      { itemId: 'hand-axe', chance: 0.3 },
      { itemId: 'studded-armor', chance: 0.08 },
    ],
    experience: 40,
    habitats: ['orc-fortress', 'thais-outskirts'],
  },
  {
    id: 'orc-spearman',
    name: 'Orc Lanceiro',
    description: 'Arremessa azagaias da segunda fileira enquanto os outros seguram a linha.',
    threat: 6,
    vitals: { hp: 80 },
    attributes: { distance: 34 },
    attacks: [{ name: 'Azagaia Arremessada', damage: '2d8+2', description: 'Alcance de dez passos.' }],
    loot: [
      { itemId: 'gold-coin', chance: 0.9, quantity: [12, 35] },
      { itemId: 'spear', chance: 0.5, quantity: [1, 3] },
    ],
    experience: 60,
    habitats: ['orc-fortress'],
  },
  {
    id: 'skeleton',
    name: 'Esqueleto',
    description: 'Ossos animados por vontade alheia. Não sente dor, não recua, não negocia.',
    threat: 6,
    vitals: { hp: 65 },
    attributes: { sword: 30 },
    attacks: [{ name: 'Lâmina Enferrujada', damage: '2d6+4' }],
    loot: [
      { itemId: 'gold-coin', chance: 0.7, quantity: [5, 20] },
      { itemId: 'jagged-sword', chance: 0.12 },
    ],
    experience: 35,
    habitats: ['thais-catacombs', 'drefia'],
    immunities: ['veneno'],
    weaknesses: ['sagrado', 'clava'],
  },
  {
    id: 'ghoul',
    name: 'Carniçal',
    description:
      'Come o que sobrou. O cheiro chega antes dele, e é o único aviso que você vai receber.',
    threat: 8,
    vitals: { hp: 100 },
    attributes: { fist: 40 },
    attacks: [
      { name: 'Garras', damage: '2d10+4' },
      { name: 'Bafo Pútrido', damage: '1d8', element: 'veneno', description: 'Aplica "envenenado".' },
    ],
    loot: [
      { itemId: 'gold-coin', chance: 0.8, quantity: [10, 40] },
      { itemId: 'health-potion', chance: 0.1 },
    ],
    experience: 85,
    habitats: ['thais-catacombs', 'drefia'],
    immunities: ['veneno'],
    weaknesses: ['sagrado'],
  },
  {
    id: 'minotaur',
    name: 'Minotauro',
    description:
      'A raça que dominava o continente antes dos humanos. Não esqueceram — e não perdoaram.',
    threat: 9,
    vitals: { hp: 120 },
    attributes: { axe: 45, shielding: 30 },
    attacks: [{ name: 'Machado de Guerra', damage: '3d8+6' }],
    loot: [
      { itemId: 'gold-coin', chance: 0.95, quantity: [20, 60] },
      { itemId: 'plate-armor', chance: 0.05 },
      { itemId: 'health-potion', chance: 0.2 },
    ],
    experience: 120,
    habitats: ['rookgaard-mines', 'mintwallin'],
  },
  {
    id: 'poison-spider',
    name: 'Aranha Venenosa',
    description: 'Do tamanho de um cão. O veneno age devagar — tempo suficiente para entrar em pânico.',
    threat: 7,
    vitals: { hp: 75 },
    attributes: { fist: 35 },
    attacks: [{ name: 'Presas', damage: '2d6', element: 'veneno', description: 'Aplica "envenenado".' }],
    loot: [
      { itemId: 'gold-coin', chance: 0.6, quantity: [5, 25] },
      { itemId: 'antidote-potion', chance: 0.1 },
    ],
    experience: 70,
    habitats: ['venore-swamp', 'rookgaard-mines'],
    immunities: ['veneno'],
  },
  {
    id: 'giant-spider',
    name: 'Aranha Gigante',
    description:
      'Ocupa o corredor inteiro. As teias de Venore não são decoração — são o mapa de onde ela ' +
      'esteve.',
    threat: 14,
    vitals: { hp: 320 },
    attributes: { fist: 70 },
    attacks: [
      { name: 'Presas Enormes', damage: '4d10+10', element: 'veneno' },
      { name: 'Teia', damage: '0', description: 'Prende o alvo por uma rodada.' },
    ],
    loot: [
      { itemId: 'gold-coin', chance: 1, quantity: [50, 150] },
      { itemId: 'stealth-ring', chance: 0.04 },
      { itemId: 'strong-health-potion', chance: 0.15 },
    ],
    experience: 900,
    habitats: ['venore-swamp', 'spider-cave'],
    immunities: ['veneno'],
    weaknesses: ['fogo'],
  },
  {
    id: 'cyclops',
    name: 'Ciclope',
    description: 'Um olho, dois punhos, nenhuma dúvida. Arranca portas do batente.',
    threat: 12,
    vitals: { hp: 260 },
    attributes: { club: 65, fist: 60 },
    attacks: [{ name: 'Marreta', damage: '4d8+12' }],
    loot: [
      { itemId: 'gold-coin', chance: 1, quantity: [40, 120] },
      { itemId: 'dwarven-shield', chance: 0.06 },
      { itemId: 'thunder-hammer', chance: 0.002 },
    ],
    experience: 600,
    habitats: ['cyclopolis', 'edron-outskirts'],
  },
  {
    id: 'bonelord',
    name: 'Senhor dos Ossos',
    description:
      'Uma esfera de olhos flutuante. Cada olho encara um alvo diferente, e todos veem através ' +
      'de paredes.',
    threat: 13,
    vitals: { hp: 270, mana: 200 },
    attributes: { magic: 55 },
    attacks: [
      { name: 'Raio Ocular', damage: '3d12+8', element: 'energia' },
      { name: 'Olhar Paralisante', damage: '0', description: 'Alvo perde a próxima ação se falhar no teste.' },
    ],
    loot: [
      { itemId: 'gold-coin', chance: 1, quantity: [50, 130] },
      { itemId: 'mana-potion', chance: 0.3, quantity: [1, 3] },
    ],
    experience: 750,
    habitats: ['drefia', 'ancient-temple'],
    immunities: ['veneno'],
  },
  {
    id: 'dragon',
    name: 'Dragão',
    description:
      'O marco. Matar o primeiro dragão é a fronteira entre "aventureiro" e "aventureiro de ' +
      'verdade" — e metade não volta da tentativa.',
    threat: 18,
    vitals: { hp: 1000 },
    attributes: { fist: 95, magic: 60 },
    attacks: [
      { name: 'Garras', damage: '5d10+15' },
      { name: 'Sopro de Fogo', damage: '6d12+20', element: 'fogo', description: 'Cone de dez passos.' },
    ],
    loot: [
      { itemId: 'gold-coin', chance: 1, quantity: [100, 300] },
      { itemId: 'dragon-scale', chance: 0.6, quantity: [1, 3] },
      { itemId: 'fire-sword', chance: 0.03 },
      { itemId: 'strong-health-potion', chance: 0.4, quantity: [1, 4] },
    ],
    experience: 3000,
    habitats: ['dragon-lair', 'thais-catacombs'],
    immunities: ['fogo'],
    weaknesses: ['gelo'],
  },
  {
    id: 'dragon-lord',
    name: 'Senhor Dragão',
    description:
      'Vermelho-escuro, antigo, inteligente. Fala — e o fato de conseguir conversar não torna a ' +
      'conversa menos perigosa.',
    threat: 24,
    vitals: { hp: 1900 },
    attributes: { fist: 120, magic: 90 },
    attacks: [
      { name: 'Garras Colossais', damage: '7d10+25' },
      { name: 'Tempestade de Fogo', damage: '8d12+30', element: 'fogo', description: 'Área ampla.' },
      { name: 'Bater de Asas', damage: '3d10', description: 'Empurra todos para trás.' },
    ],
    loot: [
      { itemId: 'gold-coin', chance: 1, quantity: [200, 500] },
      { itemId: 'dragon-scale', chance: 0.9, quantity: [2, 6] },
      { itemId: 'golden-armor', chance: 0.02 },
      { itemId: 'magic-plate-armor', chance: 0.004 },
    ],
    experience: 8000,
    habitats: ['dragon-lair', 'goroma'],
    immunities: ['fogo'],
    weaknesses: ['gelo'],
  },
  {
    id: 'warlock',
    name: 'Bruxo',
    description:
      'Humano que estudou o que não devia em Edron. Convoca fogo e ergue barreiras de mana — ' +
      'exatamente o que um Feiticeiro faria, do lado errado.',
    threat: 20,
    vitals: { hp: 1200, mana: 800 },
    attributes: { magic: 100 },
    attacks: [
      { name: 'Grande Bola de Fogo', damage: '6d12+18', element: 'fogo' },
      { name: 'Raio de Energia', damage: '5d12+15', element: 'energia' },
      { name: 'Escudo Mágico', damage: '0', description: 'Converte dano em mana por três rodadas.' },
    ],
    loot: [
      { itemId: 'gold-coin', chance: 1, quantity: [150, 400] },
      { itemId: 'wand-of-inferno', chance: 0.05 },
      { itemId: 'great-mana-potion', chance: 0.35, quantity: [1, 3] },
    ],
    experience: 4000,
    habitats: ['edron-outskirts', 'yalahar'],
  },
  {
    id: 'hydra',
    name: 'Hidra',
    description: 'Três cabeças, três ataques por rodada. Corte uma e discuta com as outras duas.',
    threat: 26,
    vitals: { hp: 2200 },
    attributes: { fist: 130, magic: 70 },
    attacks: [
      { name: 'Três Mordidas', damage: '3d10+8', description: 'Três ataques separados por rodada.' },
      { name: 'Cuspe Ácido', damage: '5d10', element: 'veneno' },
    ],
    loot: [
      { itemId: 'gold-coin', chance: 1, quantity: [200, 450] },
      { itemId: 'hailstorm-rod', chance: 0.04 },
      { itemId: 'strong-health-potion', chance: 0.5, quantity: [2, 5] },
    ],
    experience: 9000,
    habitats: ['tiquanda', 'port-hope-jungle'],
    immunities: ['veneno'],
  },
  {
    id: 'behemoth',
    name: 'Beemote',
    description:
      'Alto demais para a caverna em que vive. Anda curvado e ainda assim é a coisa mais alta ' +
      'da sala.',
    threat: 28,
    vitals: { hp: 2800 },
    attributes: { club: 150, fist: 140 },
    attacks: [
      { name: 'Punho Descendente', damage: '9d12+30' },
      { name: 'Pisada', damage: '5d12', description: 'Atinge todos ao redor.' },
    ],
    loot: [
      { itemId: 'gold-coin', chance: 1, quantity: [300, 600] },
      { itemId: 'stonecutter-axe', chance: 0.01 },
      { itemId: 'magic-plate-armor', chance: 0.003 },
    ],
    experience: 12000,
    habitats: ['behemoth-cave', 'kazordoon-depths'],
  },
  {
    id: 'demon',
    name: 'Demônio',
    description:
      'O padrão pelo qual todo o resto é medido. Se um Demônio entra na cena, o Mestre está ' +
      'dizendo algo — ouça.',
    threat: 35,
    vitals: { hp: 8200, mana: 2000 },
    attributes: { fist: 180, magic: 150 },
    attacks: [
      { name: 'Garras Infernais', damage: '12d12+40' },
      { name: 'Grande Bola de Fogo', damage: '10d12+35', element: 'fogo' },
      { name: 'Onda de Energia', damage: '9d12+30', element: 'energia', description: 'Cone amplo.' },
      { name: 'Convocar Servos', damage: '0', description: 'Traz 1d3 Carniçais ao campo.' },
    ],
    loot: [
      { itemId: 'gold-coin', chance: 1, quantity: [500, 1000] },
      { itemId: 'demon-helmet', chance: 0.005 },
      { itemId: 'fire-sword', chance: 0.08 },
      { itemId: 'golden-armor', chance: 0.04 },
    ],
    experience: 60000,
    habitats: ['demon-lair', 'goroma', 'ferumbras-citadel'],
    immunities: ['fogo', 'veneno'],
    weaknesses: ['sagrado', 'gelo'],
  },
  {
    id: 'ferumbras',
    name: 'Ferumbras',
    description:
      'O arquimago que jurou destruir Tibia e cumpriu boa parte da promessa. Morre, ressurge, ' +
      'volta a atacar. Cada geração de heróis o mata uma vez. Nenhuma o mata em definitivo.',
    threat: 50,
    vitals: { hp: 25000, mana: 10000 },
    attributes: { magic: 250, sword: 150 },
    attacks: [
      { name: 'Aniquilação', damage: '20d12+80', element: 'energia', description: 'Alvo único, sem defesa possível.' },
      { name: 'Tempestade Sombria', damage: '15d12+50', element: 'trevas', description: 'Toda a sala.' },
      { name: 'Convocar Horda', damage: '0', description: 'Traz 1d4 Demônios ao campo.' },
      { name: 'Teleporte', damage: '0', description: 'Reposiciona-se; ataques a distância falham nesta rodada.' },
    ],
    loot: [
      { itemId: 'gold-coin', chance: 1, quantity: [5000, 15000] },
      { itemId: 'demon-helmet', chance: 0.4 },
      { itemId: 'blessed-shield', chance: 0.2 },
    ],
    experience: 500000,
    habitats: ['ferumbras-citadel'],
    immunities: ['fogo', 'veneno', 'energia'],
    weaknesses: ['sagrado'],
  },
];
