import type { ItemDef } from '../types.js';

/** Itens de Tibia, do porrete de Rookgaard ao Elmo Demoníaco. */
export const tibiaItems: ItemDef[] = [
  // --- Armas iniciais -------------------------------------------------------
  {
    id: 'club',
    name: 'Porrete',
    slot: 'weapon',
    description: 'Um pedaço de madeira. Todo herói de Tibia começou com um destes.',
    weight: 2.5,
    value: 5,
    rarity: 'comum',
    damage: '1d6',
    attributeBonuses: { club: 2 },
  },
  {
    id: 'jagged-sword',
    name: 'Espada Serrilhada',
    slot: 'weapon',
    description: 'Lâmina lascada de tanto uso. Corta pior e dói mais — o que às vezes basta.',
    weight: 3.2,
    value: 30,
    rarity: 'comum',
    damage: '1d8',
    attributeBonuses: { sword: 3 },
  },
  {
    id: 'hand-axe',
    name: 'Machadinha',
    slot: 'weapon',
    description: 'Ferramenta de lenhador reconvertida. Funciona nos dois ofícios.',
    weight: 3.0,
    value: 20,
    rarity: 'comum',
    damage: '1d8',
    attributeBonuses: { axe: 3 },
  },
  {
    id: 'bow',
    name: 'Arco',
    slot: 'weapon',
    description: 'Teixo curvado e corda de tripa. Exige flechas — e paciência.',
    weight: 2.0,
    value: 80,
    rarity: 'comum',
    damage: '1d10',
    attributeBonuses: { distance: 4 },
    requires: { classIds: ['paladin', 'knight'] },
  },
  {
    id: 'crossbow',
    name: 'Besta',
    slot: 'weapon',
    description: 'Lenta para recarregar, brutal ao acertar. Atravessa cota de malha.',
    weight: 4.0,
    value: 120,
    rarity: 'incomum',
    damage: '2d6',
    attributeBonuses: { distance: 5 },
    requires: { classIds: ['paladin'] },
  },
  {
    id: 'arrow-bundle',
    name: 'Feixe de Flechas',
    slot: 'consumable',
    description: 'Cem flechas de ponta de ferro. Recolha-as depois da luta se puder.',
    weight: 5.0,
    value: 30,
    rarity: 'comum',
  },
  {
    id: 'spear',
    name: 'Azagaia',
    slot: 'weapon',
    description: 'Arremessa ou empunha. Os orcs de Rookgaard ensinaram os dois usos.',
    weight: 2.0,
    value: 15,
    rarity: 'comum',
    damage: '1d8',
    attributeBonuses: { distance: 2 },
  },

  // --- Armas de verdade -----------------------------------------------------
  {
    id: 'fire-sword',
    name: 'Espada Flamejante',
    slot: 'weapon',
    description:
      'A lâmina arde sem consumir-se. Diz-se que foi temperada nas forjas sob Kazordoon com o ' +
      'sopro de um dragão jovem — e que o dragão não sobreviveu ao processo.',
    weight: 4.5,
    value: 4000,
    rarity: 'raro',
    damage: '2d10+4',
    attributeBonuses: { sword: 8 },
    requires: { level: 30, classIds: ['knight', 'paladin'] },
  },
  {
    id: 'stonecutter-axe',
    name: 'Machado Corta-Pedra',
    slot: 'weapon',
    description: 'Machado anão de duas mãos. Feito para pedra; descobriu-se ótimo para ossos.',
    weight: 12.0,
    value: 40000,
    rarity: 'épico',
    damage: '3d10+6',
    attributeBonuses: { axe: 12 },
    requires: { level: 55, classIds: ['knight'] },
  },
  {
    id: 'thunder-hammer',
    name: 'Martelo do Trovão',
    slot: 'weapon',
    description: 'Cada golpe estala como tempestade. Anões contam que caiu do céu, e não brincam.',
    weight: 9.0,
    value: 50000,
    rarity: 'épico',
    damage: '3d8+8',
    attributeBonuses: { club: 12 },
    requires: { level: 60, classIds: ['knight'] },
  },
  {
    id: 'wand-of-vortex',
    name: 'Varinha do Vórtice',
    slot: 'weapon',
    description: 'Varinha de aprendiz. Canaliza energia bruta — pouca, mas confiável.',
    weight: 1.4,
    value: 500,
    rarity: 'comum',
    damage: '1d8',
    attributeBonuses: { magic: 3 },
    requires: { classIds: ['sorcerer'] },
  },
  {
    id: 'snakebite-rod',
    name: 'Bastão Presa-de-Cobra',
    slot: 'weapon',
    description: 'Bastão de teixo com presa engastada. Canaliza veneno.',
    weight: 1.4,
    value: 500,
    rarity: 'comum',
    damage: '1d8',
    attributeBonuses: { magic: 3 },
    requires: { classIds: ['druid'] },
  },
  {
    id: 'wand-of-inferno',
    name: 'Varinha do Inferno',
    slot: 'weapon',
    description: 'A ponta nunca esfria. Feiticeiros de Edron a tratam como rito de passagem.',
    weight: 2.5,
    value: 15000,
    rarity: 'raro',
    damage: '2d12',
    attributeBonuses: { magic: 9 },
    requires: { level: 33, classIds: ['sorcerer'] },
  },
  {
    id: 'hailstorm-rod',
    name: 'Bastão da Tempestade de Gelo',
    slot: 'weapon',
    description: 'O ar em volta congela. Druidas anciãos o carregam como cajado e como aviso.',
    weight: 2.5,
    value: 15000,
    rarity: 'raro',
    damage: '2d12',
    attributeBonuses: { magic: 9 },
    requires: { level: 33, classIds: ['druid'] },
  },

  // --- Escudos --------------------------------------------------------------
  {
    id: 'wooden-shield',
    name: 'Escudo de Madeira',
    slot: 'shield',
    description: 'Tábuas e um cinto. Vai quebrar — a questão é quando.',
    weight: 3.0,
    value: 15,
    rarity: 'comum',
    armor: 1,
    attributeBonuses: { shielding: 2 },
  },
  {
    id: 'dwarven-shield',
    name: 'Escudo Anão',
    slot: 'shield',
    description: 'Aço de Kazordoon, gravado com runas de contenção. Pesado e honesto.',
    weight: 5.5,
    value: 800,
    rarity: 'incomum',
    armor: 3,
    attributeBonuses: { shielding: 5 },
  },
  {
    id: 'blessed-shield',
    name: 'Escudo Abençoado',
    slot: 'shield',
    description:
      'Consagrado nos altares de Crunor. Reluz na presença do profano — o que já salvou mais ' +
      'expedições do que a proteção em si.',
    weight: 6.0,
    value: 90000,
    rarity: 'lendário',
    armor: 7,
    attributeBonuses: { shielding: 14 },
    requires: { level: 70 },
  },

  // --- Armaduras ------------------------------------------------------------
  {
    id: 'leather-armor',
    name: 'Armadura de Couro',
    slot: 'armor',
    description: 'Couro curtido. Protege do vento e, com sorte, de um rato.',
    weight: 4.0,
    value: 35,
    rarity: 'comum',
    armor: 2,
  },
  {
    id: 'studded-armor',
    name: 'Armadura Rebitada',
    slot: 'armor',
    description: 'Couro reforçado com rebites de ferro. O padrão dos caçadores de Venore.',
    weight: 6.0,
    value: 200,
    rarity: 'comum',
    armor: 3,
  },
  {
    id: 'plate-armor',
    name: 'Armadura de Placas',
    slot: 'armor',
    description: 'Aço articulado dos ferreiros de Thais. Cara, pesada, eficaz.',
    weight: 12.0,
    value: 1200,
    rarity: 'incomum',
    armor: 6,
    requires: { level: 20 },
  },
  {
    id: 'magic-plate-armor',
    name: 'Armadura de Placas Mágica',
    slot: 'armor',
    description:
      'O sonho de todo Cavaleiro. Encantada para não pesar e para não ceder. Praticamente ' +
      'lendária: quem tem uma não a vende, herda.',
    weight: 8.0,
    value: 500000,
    rarity: 'lendário',
    armor: 12,
    attributeBonuses: { shielding: 6 },
    requires: { level: 60, classIds: ['knight'] },
  },
  {
    id: 'druid-robe',
    name: 'Túnica Druídica',
    slot: 'armor',
    description: 'Linho tecido com fibras de carvalho ancião. Leve e permeável à magia.',
    weight: 2.0,
    value: 150,
    rarity: 'comum',
    armor: 1,
    attributeBonuses: { magic: 2 },
  },
  {
    id: 'golden-armor',
    name: 'Armadura Dourada',
    slot: 'armor',
    description: 'Ouro sobre aço. Chama atenção — o que às vezes é exatamente o objetivo.',
    weight: 11.0,
    value: 20000,
    rarity: 'épico',
    armor: 9,
    requires: { level: 45 },
  },

  // --- Elmos e acessórios ---------------------------------------------------
  {
    id: 'leather-helmet',
    name: 'Capacete de Couro',
    slot: 'helmet',
    description: 'Melhor que nada, pior que quase tudo.',
    weight: 1.5,
    value: 12,
    rarity: 'comum',
    armor: 1,
  },
  {
    id: 'magician-hat',
    name: 'Chapéu de Mago',
    slot: 'helmet',
    description: 'Pontudo, azul, absolutamente sem função defensiva. Focaliza a mente.',
    weight: 1.0,
    value: 250,
    rarity: 'comum',
    attributeBonuses: { magic: 3 },
  },
  {
    id: 'demon-helmet',
    name: 'Elmo Demoníaco',
    slot: 'helmet',
    description:
      'Arrancado da cabeça de algo que não deveria ter cabeça. Sussurra em uma língua que ' +
      'ninguém admite entender.',
    weight: 6.0,
    value: 999999,
    rarity: 'lendário',
    armor: 8,
    attributeBonuses: { sword: 5, axe: 5, club: 5 },
    requires: { level: 80 },
  },
  {
    id: 'boots-of-haste',
    name: 'Botas da Pressa',
    slot: 'boots',
    description: 'Élficas. Os pés ficam mais leves que o corpo — leva um tempo para acostumar.',
    weight: 2.0,
    value: 30000,
    rarity: 'épico',
    attributeBonuses: { distance: 4 },
    requires: { level: 40 },
  },
  {
    id: 'stealth-ring',
    name: 'Anel da Furtividade',
    slot: 'ring',
    description: 'Enquanto durar, os mortos-vivos não o notam. Nunca dura o bastante.',
    weight: 0.1,
    value: 5000,
    rarity: 'raro',
  },
  {
    id: 'amulet-of-loss',
    name: 'Amuleto da Perda',
    slot: 'amulet',
    description:
      'Quebra-se quando você morre e leva a morte no seu lugar. O item mais caro que se compra ' +
      'esperando nunca usar.',
    weight: 0.5,
    value: 50000,
    rarity: 'épico',
  },

  // --- Consumíveis ----------------------------------------------------------
  {
    id: 'health-potion',
    name: 'Poção de Vida',
    slot: 'consumable',
    description: 'Frasco vermelho, gosto de ferrugem. Fecha o que estiver aberto.',
    weight: 0.5,
    value: 45,
    rarity: 'comum',
    onUse: { vitalId: 'hp', formula: '3d20+20' },
  },
  {
    id: 'strong-health-potion',
    name: 'Poção de Vida Forte',
    slot: 'consumable',
    description: 'A versão que os Cavaleiros compram às dúzias antes de descer.',
    weight: 0.6,
    value: 100,
    rarity: 'incomum',
    onUse: { vitalId: 'hp', formula: '5d20+60' },
    requires: { level: 50 },
  },
  {
    id: 'mana-potion',
    name: 'Poção de Mana',
    slot: 'consumable',
    description: 'Azul, doce demais. Repõe o que as palavras consumiram.',
    weight: 0.5,
    value: 50,
    rarity: 'comum',
    onUse: { vitalId: 'mana', formula: '3d20+15' },
  },
  {
    id: 'great-mana-potion',
    name: 'Poção de Mana Suprema',
    slot: 'consumable',
    description: 'Destilada em Edron. Cara o bastante para doer, forte o bastante para valer.',
    weight: 0.6,
    value: 120,
    rarity: 'raro',
    onUse: { vitalId: 'mana', formula: '6d20+50' },
    requires: { level: 80 },
  },
  {
    id: 'antidote-potion',
    name: 'Poção Antídoto',
    slot: 'consumable',
    description: 'Neutraliza veneno. Os aracnídeos de Venore tornaram-na obrigatória.',
    weight: 0.4,
    value: 50,
    rarity: 'comum',
  },
  {
    id: 'brown-mushroom',
    name: 'Cogumelo Marrom',
    slot: 'consumable',
    description: 'Cresce nas cavernas de Rookgaard. Alimenta. Provavelmente.',
    weight: 0.2,
    value: 1,
    rarity: 'comum',
    onUse: { vitalId: 'hp', formula: '1d6' },
  },
  {
    id: 'rope',
    name: 'Corda',
    slot: 'misc',
    description: 'Sobe buracos. Metade das mortes em Tibia é por esquecer uma.',
    weight: 1.8,
    value: 50,
    rarity: 'comum',
  },
  {
    id: 'shovel',
    name: 'Pá',
    slot: 'misc',
    description: 'Cava pilhas de terra. O que está embaixo raramente é tesouro.',
    weight: 2.5,
    value: 50,
    rarity: 'comum',
  },
  {
    id: 'gold-coin',
    name: 'Moeda de Ouro',
    slot: 'misc',
    description: 'A moeda corrente de todo o continente.',
    weight: 0.01,
    value: 1,
    rarity: 'comum',
  },
  {
    id: 'dragon-scale',
    name: 'Escama de Dragão',
    slot: 'misc',
    description: 'Ainda morna. Ferreiros pagam bem e não perguntam a procedência.',
    weight: 0.8,
    value: 1000,
    rarity: 'raro',
  },
  {
    id: 'excalibug',
    name: 'Excalibug',
    slot: 'weapon',
    description:
      'A lâmina que nunca foi encontrada. Existem mapas, existem juramentos, existem homens que ' +
      'gastaram a vida procurando. Se ela está na sua mão, o Mestre tem algo a explicar.',
    weight: 10.0,
    value: 9999999,
    rarity: 'lendário',
    damage: '5d12+20',
    attributeBonuses: { sword: 25, shielding: 10 },
    requires: { level: 100 },
  },
];
