import type { AbilityDef } from '../types.js';

/**
 * Magias de Tibia. A invocação é canônica — os jogadores digitam a palavra de
 * poder e o Mestre reconhece.
 */
export const tibiaSpells: AbilityDef[] = [
  // --- Cura -----------------------------------------------------------------
  {
    id: 'exura',
    name: 'Cura Leve',
    incantation: 'exura',
    description: 'A primeira palavra que todo aventureiro aprende. Fecha cortes, não milagres.',
    cost: { mana: 20 },
    effect: { kind: 'heal', vitalId: 'hp', formula: '2d10+5' },
  },
  {
    id: 'exura-gran',
    name: 'Cura Intensa',
    incantation: 'exura gran',
    description: 'Fecha o que a Cura Leve só faria parar de sangrar.',
    cost: { mana: 70 },
    requires: { level: 12, classIds: ['druid', 'paladin', 'sorcerer'] },
    effect: { kind: 'heal', vitalId: 'hp', formula: '5d12+20' },
  },
  {
    id: 'exura-vita',
    name: 'Cura Suprema',
    incantation: 'exura vita',
    description: 'Traz de volta quem já estava indo. Custa quase toda a mana e vale cada gota.',
    cost: { mana: 160 },
    requires: { level: 30, classIds: ['druid'], attributes: { magic: 25 } },
    effect: { kind: 'heal', vitalId: 'hp', formula: '10d15+60' },
    cooldown: 2,
  },
  {
    id: 'exura-sio',
    name: 'Cura em Companheiro',
    incantation: 'exura sio "nome"',
    description: 'Cura à distância. Exige ver o alvo — e acertar o nome.',
    cost: { mana: 140 },
    requires: { level: 24, classIds: ['druid'] },
    effect: { kind: 'heal', vitalId: 'hp', formula: '8d12+40' },
  },
  {
    id: 'exura-gran-mas-res',
    name: 'Cura em Massa',
    incantation: 'exura gran mas res',
    description: 'Onda de vida que alcança todo o grupo. Marca registrada do Druida Ancião.',
    cost: { mana: 200 },
    requires: { level: 36, classIds: ['druid'] },
    effect: { kind: 'heal', vitalId: 'hp', formula: '6d12+30' },
    cooldown: 3,
  },

  // --- Ataque corpo a corpo -------------------------------------------------
  {
    id: 'exori-ico',
    name: 'Golpe Feroz',
    incantation: 'exori ico',
    description: 'Concentra a força num único golpe. O Cavaleiro empurra mana para dentro do braço.',
    cost: { mana: 30 },
    requires: { level: 8, classIds: ['knight'] },
    effect: { kind: 'damage', formula: '3d10+10', area: 'single' },
  },
  {
    id: 'exori',
    name: 'Berserk',
    incantation: 'exori',
    description: 'Gira em torno de si e acerta tudo ao alcance. Não escolhe alvos — só direções.',
    cost: { mana: 115 },
    requires: { level: 35, classIds: ['knight'] },
    effect: { kind: 'damage', formula: '4d12+15', area: 'area' },
    cooldown: 2,
  },
  {
    id: 'exori-gran',
    name: 'Golpe Poderoso',
    incantation: 'exori gran',
    description: 'Tudo num só golpe. Se errar, você fica exposto por uma rodada inteira.',
    cost: { mana: 340 },
    requires: { level: 90, classIds: ['knight'] },
    effect: { kind: 'damage', formula: '8d12+40', area: 'single' },
    cooldown: 4,
  },

  // --- Ataque à distância / elemental --------------------------------------
  {
    id: 'exori-flam',
    name: 'Chama',
    incantation: 'exori flam',
    description: 'Uma esfera de fogo do tamanho de um punho. Barata e constante.',
    cost: { mana: 20 },
    requires: { classIds: ['sorcerer'] },
    effect: { kind: 'damage', formula: '2d8+4', element: 'fogo', area: 'single' },
  },
  {
    id: 'exori-frigo',
    name: 'Lasca de Gelo',
    incantation: 'exori frigo',
    description: 'Estilhaço de gelo. Retarda tanto quanto fere.',
    cost: { mana: 20 },
    requires: { classIds: ['druid'] },
    effect: { kind: 'damage', formula: '2d8+4', element: 'gelo', area: 'single' },
  },
  {
    id: 'exori-vis',
    name: 'Míssil Energético',
    incantation: 'exori vis',
    description: 'Energia pura. Ignora armadura, não ignora resistência mágica.',
    cost: { mana: 40 },
    requires: { level: 12, classIds: ['sorcerer'] },
    effect: { kind: 'damage', formula: '3d10+8', element: 'energia', area: 'single' },
  },
  {
    id: 'exevo-flam-hur',
    name: 'Onda de Fogo',
    incantation: 'exevo flam hur',
    description: 'Cone de chamas à frente. Cuidado com quem está no caminho.',
    cost: { mana: 55 },
    requires: { level: 18, classIds: ['sorcerer'] },
    effect: { kind: 'damage', formula: '4d10+12', element: 'fogo', area: 'area' },
  },
  {
    id: 'exevo-frigo-hur',
    name: 'Onda de Gelo',
    incantation: 'exevo frigo hur',
    description: 'O ar congela num cone à frente. Silencioso, ao contrário do fogo.',
    cost: { mana: 55 },
    requires: { level: 18, classIds: ['druid'] },
    effect: { kind: 'damage', formula: '4d10+12', element: 'gelo', area: 'area' },
  },
  {
    id: 'exevo-gran-mas-frigo',
    name: 'Tempestade de Gelo',
    incantation: 'exevo gran mas frigo',
    description:
      'A grande magia de área do Druida. Uma nevasca desce sobre tudo num raio de dez passos. ' +
      'Custa caro e limpa salas.',
    cost: { mana: 530 },
    requires: { level: 60, classIds: ['druid'], attributes: { magic: 40 } },
    effect: { kind: 'damage', formula: '10d15+50', element: 'gelo', area: 'area' },
    cooldown: 4,
  },
  {
    id: 'exevo-gran-mas-flam',
    name: 'Tempestade de Fogo',
    incantation: 'exevo gran mas flam',
    description: 'O equivalente do Feiticeiro. Um círculo de chamas que apaga encontros inteiros.',
    cost: { mana: 530 },
    requires: { level: 60, classIds: ['sorcerer'], attributes: { magic: 40 } },
    effect: { kind: 'damage', formula: '10d15+50', element: 'fogo', area: 'area' },
    cooldown: 4,
  },
  {
    id: 'exevo-con',
    name: 'Conjurar Flechas',
    incantation: 'exevo con',
    description: 'Materializa munição a partir de mana. O fim do problema logístico do Paladino.',
    cost: { mana: 100 },
    requires: { level: 13, classIds: ['paladin'] },
    effect: { kind: 'utility', description: 'Conjura um feixe de flechas mágicas.' },
  },
  {
    id: 'exori-san',
    name: 'Tiro Sagrado',
    incantation: 'exori san',
    description: 'Projétil sagrado. Devastador contra mortos-vivos e demônios.',
    cost: { mana: 40 },
    requires: { level: 20, classIds: ['paladin'] },
    effect: { kind: 'damage', formula: '3d12+10', element: 'sagrado', area: 'single' },
  },
  {
    id: 'exevo-mas-san',
    name: 'Chuva de Estrelas',
    incantation: 'exevo mas san',
    description: 'Estrelas sagradas caem sobre a área. O arsenal completo do Paladino Real.',
    cost: { mana: 370 },
    requires: { level: 50, classIds: ['paladin'] },
    effect: { kind: 'damage', formula: '8d12+35', element: 'sagrado', area: 'area' },
    cooldown: 3,
  },

  // --- Suporte e utilidade --------------------------------------------------
  {
    id: 'utevo-lux',
    name: 'Luz',
    incantation: 'utevo lux',
    description: 'Uma esfera luminosa. Nas minas, isso é a diferença entre explorar e cair.',
    cost: { mana: 20 },
    effect: { kind: 'utility', description: 'Ilumina um raio de cinco passos por uma hora.' },
  },
  {
    id: 'utevo-gran-lux',
    name: 'Grande Luz',
    incantation: 'utevo gran lux',
    description: 'Ilumina uma sala inteira. Também anuncia sua chegada a todos nela.',
    cost: { mana: 60 },
    requires: { level: 13 },
    effect: { kind: 'utility', description: 'Ilumina um raio de dez passos por duas horas.' },
  },
  {
    id: 'utani-hur',
    name: 'Pressa',
    incantation: 'utani hur',
    description: 'Acelera os passos. Fugir também é uma tática.',
    cost: { mana: 60 },
    requires: { level: 14 },
    effect: { kind: 'buff', description: 'Movimento acelerado; +2 em testes de esquiva.', duration: 10 },
  },
  {
    id: 'utani-gran-hur',
    name: 'Pressa Intensa',
    incantation: 'utani gran hur',
    description: 'O mundo desacelera. Dura pouco e custa muito.',
    cost: { mana: 100 },
    requires: { level: 20 },
    effect: { kind: 'buff', description: 'Movimento muito acelerado; +4 em testes de esquiva.', duration: 6 },
  },
  {
    id: 'utamo-vita',
    name: 'Escudo Mágico',
    incantation: 'utamo vita',
    description:
      'Converte mana em barreira: o dano vai para a mana antes de ir para a vida. O que mantém ' +
      'Feiticeiros vivos.',
    cost: { mana: 50 },
    requires: { level: 14, classIds: ['sorcerer', 'druid'] },
    effect: { kind: 'buff', description: 'Dano recebido consome mana antes de vida.', duration: 20 },
  },
  {
    id: 'exana-pox',
    name: 'Antídoto',
    incantation: 'exana pox',
    description: 'Neutraliza veneno. Aranhas gigantes tornaram esta palavra obrigatória.',
    cost: { mana: 30 },
    requires: { classIds: ['druid', 'paladin'] },
    effect: { kind: 'utility', description: 'Remove a condição "envenenado".' },
  },
  {
    id: 'exana-flam',
    name: 'Extinguir Chamas',
    incantation: 'exana flam',
    description: 'Apaga o fogo que consome. Dolorosamente específica, ocasionalmente vital.',
    cost: { mana: 30 },
    requires: { level: 15 },
    effect: { kind: 'utility', description: 'Remove a condição "em chamas".' },
  },
  {
    id: 'exiva',
    name: 'Localizar Pessoa',
    incantation: 'exiva "nome"',
    description: 'Aponta a direção de alguém no mesmo continente. Não diz o quão longe.',
    cost: { mana: 20 },
    requires: { level: 8 },
    effect: { kind: 'utility', description: 'Revela a direção aproximada de um alvo nomeado.' },
  },
  {
    id: 'utana-vid',
    name: 'Invisibilidade',
    incantation: 'utana vid',
    description:
      'Some da vista. Não some do olfato, da audição, nem da percepção dos mortos-vivos — que ' +
      'não usam olhos.',
    cost: { mana: 440 },
    requires: { level: 35, classIds: ['sorcerer', 'druid'] },
    effect: { kind: 'buff', description: 'Invisível para criaturas que dependem de visão.', duration: 20 },
  },
  {
    id: 'adura-vita',
    name: 'Bênção do Templo',
    incantation: 'adura vita',
    description:
      'Rito nos altares. Reduz o que se perde ao morrer — a diferença entre um tropeço e uma ' +
      'carreira arruinada.',
    cost: { mana: 0 },
    effect: { kind: 'utility', description: 'Aplica a bênção do templo; reduz perdas na morte.' },
  },
];
